# Generated by Django 4.1.7 on 2023-03-11 08:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("emailer", "0001_migrations"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkEmailer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_file",
                    models.FileField(
                        help_text="please upload excel or csv file",
                        upload_to="emailed_files",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["csv", "xls", "xlsx"]
                            )
                        ],
                        verbose_name="File",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            (".xlsx", ".xlsx"),
                            (".xls", ".xls"),
                            (".csv", ".csv"),
                        ],
                        max_length=10,
                        verbose_name="File Type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_mailers",
                        to="emailer.emailtemplate",
                    ),
                ),
            ],
        ),
    ]
