# Generated by Django 4.1.7 on 2023-03-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emailer", "0002_migrations"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkemailer",
            name="invalid_emails",
            field=models.IntegerField(
                default=0,
                help_text="Number of invalid emails from the file",
                verbose_name="Invalid Emails",
            ),
        ),
        migrations.AddField(
            model_name="bulkemailer",
            name="mails_failed",
            field=models.IntegerField(
                default=0,
                help_text="Number of failed emails sent from the valid emails",
                verbose_name="Mails Failed",
            ),
        ),
        migrations.AddField(
            model_name="bulkemailer",
            name="mails_sent",
            field=models.IntegerField(
                default=0,
                help_text="Number of successful emails sent from the valid emails",
                verbose_name="Mails Sent",
            ),
        ),
        migrations.AddField(
            model_name="bulkemailer",
            name="valid_emails",
            field=models.IntegerField(
                default=0,
                help_text="Number of valid emails from the file",
                verbose_name="Valid Emails",
            ),
        ),
    ]
