# Generated by Django 4.1.7 on 2023-03-11 12:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("emailer", "0004_migrations"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dailyreport",
            old_name="total_emails",
            new_name="total_requests",
        ),
    ]
