# Generated by Django 4.1.7 on 2023-03-11 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("emailer", "0005_migrations"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="failed_count",
            field=models.IntegerField(
                default=0,
                help_text="Total count of failed emails",
                verbose_name="failed count",
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="success_count",
            field=models.IntegerField(
                default=0,
                help_text="Total count of successful emails sent",
                verbose_name="success count",
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="success_rate",
            field=models.FloatField(
                default=0.0,
                help_text="Success rate of emails sent",
                verbose_name="success rate",
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="total_count",
            field=models.IntegerField(
                default=0,
                help_text="Total count of emails sent",
                verbose_name="total count",
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="total_requests",
            field=models.IntegerField(
                default=0,
                help_text="Total number of valid emails",
                verbose_name="Total Requests",
            ),
        ),
    ]
